### ISSUE TITLE
kill process when user clicks X

### ISSUE THREAD

**Issue by Buster-de** [linuxmuster/linuxmuster-linbo-gui#60] opened 2021-04-22 21:08 UTC
I had a situation where torrent seed was canceled/restartet on the server. This lead to 0 KB/s torrent download speed for the client. After timeout the client retried with rsync.

Now i wanted to stop rsync and have the client retry with torrent (set as default download type in start.conf). I clicked the X to abort, but the rsync download did not stop. Using iftop on the server i could see the download still running although the gui was in main menu.

I understand that there might be some processes, where aborting might not be a good idea (partitioning, formatting). But downloading and cloning can be repeated safely, imho.

**Comment by dorianim** [comment] 2021-04-23 04:34
Duplicate of #57

**Comment by dorianim** [comment] 2021-04-23 05:23
Sorry, I marked it as a duplicate, although its not.

**Comment by dorianim** [comment] 2021-04-23 05:24
I think this is a problem with linbo. When you klick the X, the GUI kills the underlying linbo_cmd process, this should stop running downloads.
I will take a look at this but I think this is an issue with Linbo.

**Comment by dorianim** [comment] 2021-04-23 08:13
As you can see here:
https://github.com/linuxmuster/linuxmuster-linbo-gui/blob/7602ef131c4cd514f291af78c2233cafc88955e7/sources/backend/linbobackend.cpp#L491

I am killing the linbo_cmd process once the user clicks "X". Please move this issue to the linbo repo.

**Closed as completed by dorianim** 2021-04-23 08:13 UTC
